#ifndef TYPECONSTANTS_H_INCLUDED
#define TYPECONSTANTS_H_INCLUDED

#define SERIALIZABLE_OBJECT 0
#define SERIALIZABLE_INTEGER 1
#define SERIALIZABLE_REAL 2
#define SERIALIZABLE_STRING 3
#define SERIALIZABLE_RAW_BYTE_BUFFER 4
#define SERIALIZABLE_SIGNAL 5
typedef int Type;

#endif // TYPECONSTANTS_H_INCLUDED
