.TH "A" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
A \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBB\fP, \fBB\fP\fC [virtual]\fP, and \fBB\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBA\fP (int v)"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "\fBA\fP (int v)"
.br
.ti -1c
.RI "void \fBmethod\fP (int prova=9)"
.br
.ti -1c
.RI "\fBA\fP (int a)"
.br
.ti -1c
.RI "\fBA\fP (int v)"
.br
.ti -1c
.RI "\fBA\fP \fBmetodo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBval\fP"
.br
.ti -1c
.RI "int \fBvalore\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBa\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
