.TH "base" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
base \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBderivataPrima< T >\fP, and \fBderivataPrima< int >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBwhoAmI\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
