.TH "derivataPrima" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
derivataPrima \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBbase\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBderivataPrima\fP (T &reference)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "T & \fBmembro\fP"
.br
.ti -1c
.RI "bool \fBuserReference\fP"
.br
.in -1c

.SS "template<typename T> class derivataPrima< T >"


.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
