.TH "Publisher" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Publisher \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCallableService< Stub >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPublisher\fP (string RegistryAddress)"
.br
.ti -1c
.RI "void \fBsetPublishingMode\fP (PublishingMode publishingModeToSet)"
.br
.ti -1c
.RI "void \fBaddObjectToPublish\fP (\fBRegistrableObject\fP *objectToPublish)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBbind\fP ()"
.br
.ti -1c
.RI "string \fBpublishingModeToString\fP (PublishingMode publishingModeToConvert)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "PublishingMode \fBpublishingMode\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
