.TH "RegistrableObject" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegistrableObject \- 
.PP
Intefaccia per oggetti registrabili.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <RegistrableObject.h>\fP
.PP
Inherited by \fBB\fP, \fBRegistrablePoolableCallableSkeletonWrapper< T >\fP, \fBRegistrableSkeleton\fP, and \fBRegistrableSkeletonThreadPool< T, poolSize >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual string \fBgetRegistrationInfo\fP ()=0"
.br
.in -1c
.SH "Detailed Description"
.PP 
Intefaccia per oggetti registrabili. 

L' interfaccia \fBRegistrableObject\fP fornisce, alle classi che la implementano, il metodo 'getRegistrationInfo()'. 
.SH "Member Function Documentation"
.PP 
.SS "virtual string RegistrableObject::getRegistrationInfo ()\fC [pure virtual]\fP"Il metodo consente di ottenere dalla classe che implementa l'interfaccia le informazioni relative alla registrazione.
.PP
\fBReturns:\fP
.RS 4
Informazioni relative alla registrazione. 
.RE
.PP

.PP
Implemented in \fBRegistrablePoolableCallableSkeletonWrapper< T >\fP, \fBRegistrableSkeleton\fP, \fBRegistrableSkeletonThreadPool< T, poolSize >\fP, and \fBB\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
