.TH "RegistrableSkeleton" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegistrableSkeleton \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRegistrableObject\fP, and \fBSkeleton\fP.
.PP
Inherited by \fBRegistrablePoolableCyclicCallableSkeleton\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegistrableSkeleton\fP (string serviceIDToSet)"
.br
.ti -1c
.RI "\fBRegistrableSkeleton\fP (string serviceIDToSet, \fBTcpIpPassiveSocket\fP *listeningSocketToShare)"
.br
.ti -1c
.RI "string \fBgetRegistrationInfo\fP ()"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string RegistrableSkeleton::getRegistrationInfo ()\fC [virtual]\fP"Il metodo consente di ottenere dalla classe che implementa l'interfaccia le informazioni relative alla registrazione.
.PP
\fBReturns:\fP
.RS 4
Informazioni relative alla registrazione. 
.RE
.PP

.PP
Implements \fBRegistrableObject\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
