.TH "RegisterManager" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegisterManager \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBRegistrablePoolableCyclicCallableSkeleton\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBreceiveParameters\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBdoService\fP ()"
.br
.ti -1c
.RI "virtual void \fBeditMap\fP (string command)"
.br
.ti -1c
.RI "virtual void \fBsearchInMap\fP ()"
.br
.in -1c

.SS "template<template< typename, typename > class RegisterMap> class RegisterManager< RegisterMap >"


.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
