.TH "RegObj" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RegObj \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBRegSkel\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBreg\fP ()=0"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
