.TH "SocketException" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SocketException \- 
.PP
Situazioni erronee nella creazione e nell' utilizzo del socket.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <SocketException.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Situazioni erronee nella creazione e nell' utilizzo del socket. 

L' eccezione \fBSocketException\fP segnala situazioni erronee nella creazione e nell' utilizzo del socket. 
.SH "Member Function Documentation"
.PP 
.SS "virtual const char* SocketException::what () const  throw ()\fC [inline, virtual]\fP"Specifica la tipologia di errore. 

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
