.TH "UnknownType" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
UnknownType \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual const char * \fBwhat\fP () const   throw ()"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
