.TH "B" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
B \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBA\fP, \fBRegistrableObject\fP, \fBA\fP, and \fBA\fP.
.PP
Inherited by \fBC< T >\fP, \fBC< B >\fP\fC [virtual]\fP, and \fBC< B >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBB\fP (int vA, int vB)"
.br
.ti -1c
.RI "\fBB\fP (int a)"
.br
.ti -1c
.RI "string \fBgetRegistrationInfo\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBvalB\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "string B::getRegistrationInfo ()\fC [inline, virtual]\fP"Il metodo consente di ottenere dalla classe che implementa l'interfaccia le informazioni relative alla registrazione.
.PP
\fBReturns:\fP
.RS 4
Informazioni relative alla registrazione. 
.RE
.PP

.PP
Implements \fBRegistrableObject\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
