.TH "ByteArray" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ByteArray \- 
.PP
Array di byte.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <ByteArray.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBByteArray\fP (const \fBByteArray\fP &byteArrayToCopy)"
.br
.ti -1c
.RI "\fBByteArray\fP (uint64_t length)"
.br
.ti -1c
.RI "\fBByteArray\fP (void *byteArrayToSet, uint64_t lengthToSet)"
.br
.ti -1c
.RI "byte & \fBoperator[]\fP (const uint64_t index)"
.br
.ti -1c
.RI "void \fBoperator=\fP (const \fBByteArray\fP &byteArrayToCopy)"
.br
.ti -1c
.RI "void \fBerase\fP ()"
.br
.ti -1c
.RI "void \fBappend\fP (byte *bufferToUse, uint64_t startingPosition, uint64_t fragmentLength)"
.br
.ti -1c
.RI "uint64_t \fBgetLength\fP ()"
.br
.ti -1c
.RI "const byte * \fBgetPointer\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Array di byte. 

La classe \fBByteArray\fP gestisce array di byte. 

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
