.TH "CallableService" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CallableService \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCallableObject\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCallableService\fP (string serviceIdToSet)"
.br
.ti -1c
.RI "\fBCallableService\fP (string serviceIdToSet, string ServiceRegistryToSet)"
.br
.ti -1c
.RI "virtual void \fBoperator()\fP ()=0"
.br
.in -1c

.SS "template<typename T> class CallableService< T >"


.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
