.TH "CalServ" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
CalServ \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBCalObj\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCalServ\fP (string ID)"
.br
.ti -1c
.RI "void \fBoperator()\fP ()=0"
.br
.in -1c

.SS "template<typename T> class CalServ< T >"


.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
