.TH "GenericSerializableRefenceLayer" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GenericSerializableRefenceLayer \- 
.PP
Classe template che implementa parte dei metodi esposti dall' intefaccia \fBSerializableObject\fP.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <GenericSerializableReferenceLayer.h>\fP
.SH "Detailed Description"
.PP 
Classe template che implementa parte dei metodi esposti dall' intefaccia \fBSerializableObject\fP. 

Il layer è pensato per rendere serializzabili dei riferimenti ad oggetti locali. I metodi esposti da \fBSerializableObject\fP ed implementati dal layer sono indipendenti dal particolare tipo del riferimento gestito. I rimanenti, che invece dipendono dal particolare tipo, verranno implementati da classi derivate dal layer secondo strategie opportune. 

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
