.TH "MonitoredExtensibleMap" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
MonitoredExtensibleMap \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBExtensibleMap< Key, SchedulingInformation, Element >\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual Element \fBoperator[]\fP (Key searchingKey)"
.br
.ti -1c
.RI "virtual \fBlist\fP< Element > \fBgetAllElementsIn\fP (Key searchingKey)"
.br
.ti -1c
.RI "virtual void \fBinsertElement\fP (Key selectingKey, Element elementToInsert)"
.br
.ti -1c
.RI "virtual void \fBclearElement\fP (Key selectingKey, Element elementToClear)"
.br
.ti -1c
.RI "virtual void \fBclearElementList\fP (Key selectingKey)"
.br
.ti -1c
.RI "void \fBprint\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual Element \fBselectionOperatorImplementation\fP (Key searchingKey)=0"
.br
.ti -1c
.RI "virtual void \fBinsertElementImplementation\fP (Key selectingKey, Element elementToInsert)=0"
.br
.ti -1c
.RI "virtual void \fBclearElementImplementation\fP (Key selectingKey, Element elementToClear)=0"
.br
.in -1c

.SS "template<typename Key, typename SchedulingInformation, typename Element> class MonitoredExtensibleMap< Key, SchedulingInformation, Element >"


.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
