.TH "RRFIFOMonitoredExtensibleMap" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
RRFIFOMonitoredExtensibleMap \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBMonitoredExtensibleMap< Key, int, Element >\fP.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "Element \fBselectionOperatorImplementation\fP (Key searchingKey)"
.br
.ti -1c
.RI "void \fBinsertElementImplementation\fP (Key searchingKey, Element elementToInsert)"
.br
.ti -1c
.RI "void \fBclearElementImplementation\fP (Key selectingKey, Element elementToClear)"
.br
.in -1c

.SS "template<typename Key, typename Element> class RRFIFOMonitoredExtensibleMap< Key, Element >"


.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
