.TH "soa-plus-plus/SerializableObjects/DeserializationStrategies/SerializableObjectBuilder.h" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
soa-plus-plus/SerializableObjects/DeserializationStrategies/SerializableObjectBuilder.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <map>\fP
.br
\fC#include '../../ObjectInterfaces/SerializableObject/SerializableObject.h'\fP
.br
\fC#include '../TypeConstants.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSerializableObjectBuilder\fP"
.br
.RI "\fIClasse base del sistema di costruzione di \fBSerializableObject\fP. \fP"
.in -1c
.SH "Detailed Description"
.PP 
\fBAuthor:\fP
.RS 4
Sacco Cosimo <cosimosacco@gmail.com>, Silvestri Davide <davidesil.web@gmail.com>
.RE
.PP
.SH "LICENSE"
.PP
This program is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
.PP
This program is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR \fBA\fP PARTICULAR PURPOSE. See the GNU General Public License for more details.
.PP
You should have received a copy of the GNU General Public License along with this program. If not, see <http://www.gnu.org/licenses/>. 
.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
