.TH "Skeleton" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Skeleton \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBService\fP.
.PP
Inherited by \fBCallableService< Skeleton >\fP\fC [virtual]\fP, and \fBRegistrableSkeleton\fP\fC [virtual]\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSkeleton\fP (string serviceIDToSet)"
.br
.ti -1c
.RI "\fBSkeleton\fP (string serviceIDToSet, \fBTcpIpPassiveSocket\fP *listeningSocketToShare)"
.br
.ti -1c
.RI "\fBSkeleton\fP (string serviceIDToSet, string IPAddress, int port, int backlog)"
.br
.ti -1c
.RI "void \fBshareListeningSocket\fP (\fBTcpIpPassiveSocket\fP *listeningSocketToShare)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBbind\fP ()"
.br
.ti -1c
.RI "void \fBprotocol\fP ()"
.br
.ti -1c
.RI "virtual void \fBdoService\fP ()=0"
.br
.ti -1c
.RI "void \fBaddParameter\fP (\fBSerializableObject\fP *parameterToAdd, Direction parameterDirection)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBTcpIpPassiveSocket\fP * \fBlisteningSocket\fP"
.br
.ti -1c
.RI "bool \fBsharedListeningSocket\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
