.TH "StreamStub" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
StreamStub \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBStub\fP.
.PP
Inherited by \fBParticularServiceStreamStub\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStreamStub\fP (string serviceIDToSet, string serviceRegistryAddressToSet)"
.br
.ti -1c
.RI "virtual void \fBoperator<<\fP (int &value)"
.br
.ti -1c
.RI "virtual void \fBoperator<<\fP (double &value)"
.br
.ti -1c
.RI "virtual void \fBoperator<<\fP (string &value)"
.br
.ti -1c
.RI "virtual void \fBoperator<<\fP (\fBByteArray\fP &value)"
.br
.ti -1c
.RI "virtual void \fBoperator<<\fP (\fBBadRequestSignal\fP &value)"
.br
.ti -1c
.RI "virtual void \fBoperator>>\fP (int &value)"
.br
.ti -1c
.RI "virtual void \fBoperator>>\fP (double &value)"
.br
.ti -1c
.RI "virtual void \fBoperator>>\fP (string &value)"
.br
.ti -1c
.RI "virtual void \fBoperator>>\fP (\fBByteArray\fP &value)"
.br
.ti -1c
.RI "virtual void \fBoperator>>\fP (\fBBadRequestSignal\fP &value)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
