.TH "TcpIpSocket" 3 "Tue Jul 5 2011" "soa-plus-plus" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TcpIpSocket \- 
.PP
Socket TCP/IP.  

.SH SYNOPSIS
.br
.PP
.PP
\fC#include <TcpIpSocket.h>\fP
.PP
Inherited by \fBTcpIpActiveSocket\fP, and \fBTcpIpPassiveSocket\fP.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTcpIpSocket\fP ()"
.br
.ti -1c
.RI "\fBTcpIpSocket\fP (int NOP)"
.br
.ti -1c
.RI "\fB~TcpIpSocket\fP ()"
.br
.ti -1c
.RI "virtual string \fBgetAddress\fP ()=0"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "int \fBsocketDescriptor\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Socket TCP/IP. 

La classe astratta \fBTcpIpSocket\fP mantiene un descrittore di file relativo al socket gestito. 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "TcpIpSocket::TcpIpSocket ()"Costruttore. Crea il socket. 
.SS "TcpIpSocket::TcpIpSocket (intNOP)"Costruttore fittizio. Non istanzia alcun socket.
.PP
\fBParameters:\fP
.RS 4
\fINOP\fP Prametro fittizio. 
.RE
.PP

.SS "TcpIpSocket::~TcpIpSocket ()"Distruttore. Chiude il socket. 
.SH "Member Function Documentation"
.PP 
.SS "virtual string TcpIpSocket::getAddress ()\fC [pure virtual]\fP"Ritorna una rappresentazione ascii dell' indirizzo associato al socket.
.PP
\fBReturns:\fP
.RS 4
Indirizzo associato al socket. 
.RE
.PP

.PP
Implemented in \fBTcpIpActiveSocket\fP, and \fBTcpIpPassiveSocket\fP.

.SH "Author"
.PP 
Generated automatically by Doxygen for soa-plus-plus from the source code.
